baseurl = "http://ivan.fraixed.es/hugo-resources"
languageCode = "en-us"
title = "Hugo Resources"
pygmentsstyle = "tango"
googleAnalytics = "UA-54405610-5"

[params]
  google_tag_manager = "GMT-XXXXX"
